### ISSUE TITLE
Failing purchased

### ISSUE THREAD

**Issue by mohammadreza** [PHELAT/Poolakey#20]
**Describe the bug**
Hi, recently I tried to implement my IAB using Poolakey library but I think something's wrong here.
After a successful purchase in payment `onActivtyResult` method, right in the `purchaseFailed` callback I faced with an odd error message in localizedMessage:
`purchase was hijacked and it's not a valid purchase` 

**Expected behavior**
I thought that after a successful purchase I should back to `purchaseSucceed` callback but I didn't. though all thing are sounds good.

**Versions**
- Version of the library that your are using: 1.0.0-alpha03
- API Version of the Android device that you have tested on: API 28

**Comment by PHELAT** [comment]
Hi,
There has to be an issue with your RSA public key, make sure that you have provided that correctly through `PaymentConfiguration` class. This error happens because of invalidity of the received data or inability to verify the data which in this case, it's probably something wrong with your RSA public key.

**Comment by mohammadreza** [comment]
Thanks for your quick response. you were right, there were a mistake in providing RSA key.
